### ISSUE TITLE
Recursively reference properties do not work

### ISSUE THREAD

**Issue by JefStat** [01alchemist/sls-yaml#26]
Documentation from the serverless framework

[${file(../../sls-config/stuff.yml):${self:provider.stage}-dynamodb-table}](https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-properties-in-other-files)

The following example doesn't work
```
provider:
  name: aws
  environment:
    MY_SECRET: ${file(./config.${opt:stage, 'dev'}.json):CREDS}
```

The `:CREDS` is appended to the file path resulting in a file not found exception
